<?php
/**
 * @copyright Copyright (c) 2012 Adrian Speyer.
 * @copyright Copyright (c) 2018 Thiago Contardi.
 * @license http://www.gnu.org/licenses/gpl-3.0.html GPL v3 or later
 *
 * @see https://matomo.org/faq/reports/advanced-manually-tracking-ecommerce-actions-in-matomo/
 * @see https://matomo.org/blog/2017/04/different-ways-embedding-piwik-tracking-code-faster-website-performance/
 */
/** @var Matomo_Analytics_Block_Script $this */
?>
<?php if (! $this->helper('core/cookie')->isUserNotAllowSaveCookie() && $this->getSiteId()): ?>
    <script nonce="<?= $this->getNonce() ?>">
        var _paq = window._paq = window._paq || [];
        (function () {
            var u = "<?= $this->getInstallPath() ?>";
            _paq.push(['setSiteId', <?= $this->getSiteId() ?>]);
            _paq.push(['setTrackerUrl', u + 'matomo.php']);

            <?php if ($this->getRequest()->getRouteName() === 'checkout'): ?>
            <?= $this->getEcommerceCartUpdate() ?>
            <?php endif ?>
            <?= $this->getOrdersTrackingCode() ?>
            <?= $this->getProductPageview() ?>
            <?= $this->getCategoryPageview() ?>

            <?php if ($this->getSearchResultCount() > 0): ?>
                _paq.push(['setCustomUrl', '' + document.URL + '&search_count=<?= $this->getSearchResultCount() ?>']);
            <?php endif ?>

            <?php if ($this->is404()): ?>
                _paq.push(['setDocumentTitle', '404/URL = ' + String(document.location.pathname + document.location.search).replace(/\//g, "%2f") + '/From = ' + String(document.referrer).replace(/\//g, "%2f")]);
            <?php endif ?>

            _paq.push(['trackPageView']);
            _paq.push(['enableLinkTracking']);
            _paq.push(['trackVisibleContentImpressions']);
            function embedTrackingCode() {
               var d=document, g=d.createElement("script"), s=d.getElementsByTagName("script")[0]; g.type="text/javascript";
               g.defer=true; g.async=true; g.src=u+"matomo.js"; s.parentNode.insertBefore(g,s);
            }

            if (window.addEventListener) {
                window.addEventListener("load", embedTrackingCode, false);
            } else if (window.attachEvent) {
                window.attachEvent("onload", embedTrackingCode);
            } else {
                embedTrackingCode();
            }
        })();
    </script>
    <noscript><p><img src="<?= $this->getInstallPath() ?>matomo.php?idsite=<?= $this->getSiteId() ?>&rec=1" style="border:0" alt="" /></p></noscript>
<?php endif ?>
